# Generated by Django 3.1 on 2020-10-09 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0004_remove_place_information_end_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='authentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_code', models.CharField(max_length=255)),
                ('isCompleted', models.BooleanField(default=False)),
                ('which_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='place_information',
        ),
    ]
